# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MRZScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MRZScanner
  pod 'DynamsoftLabelRecognizerBundle','3.2.3001'
  pod 'DynamsoftCodeParser','2.2.11'
  pod 'DynamsoftCodeParserDedicator','1.2.21'

end
