# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DriversLicenseScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DriversLicenseScanner
  pod 'DynamsoftBarcodeReaderBundle', '10.2.1101'
  pod 'DynamsoftCodeParser', '2.2.11'
  pod 'DynamsoftCodeParserDedicator', '1.2.21'

end
