# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VINScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VINScanner
  pod 'DynamsoftBarcodeReaderBundle', '10.2.1101'
  pod 'DynamsoftLabelRecognizerBundle', '3.2.3001'
  pod 'DynamsoftCodeParser', '2.2.10'
  pod 'DynamsoftCodeParserDedicator', '1.2.20'


end
